### PR TITLE
Set-up CI

### PR DESCRIPTION
**Pull request by anbergem**
#6

### CODE REVIEW

**Review by vegarsti — COMMENTED** [review]
😍 awesome! I don't understand why this doesn't work, though...

We may want to use Docker images, see [e.g. here](https://medium.com/ai2-blog/ci-with-github-actions-for-research-code-a8460c21c6ba). Then we get a reproducible process than we can do locally as well.

But this should work anyway 🤔

**Comment by anbergem** [comment]
> 😍 awesome! I don't understand why this doesn't work, though...

It was because no tests run doesn't return status `0`, but `5`.

> We may want to use Docker images, see [e.g. here](https://medium.com/ai2-blog/ci-with-github-actions-for-research-code-a8460c21c6ba). Then we get a reproducible process than we can do locally as well.

Do we though? Isn't that just for more niche (correct spelling) projects, where the software has to run on certain hardware? But didn't read the whole article, though.

**Comment by vegarsti** [comment]
Ah, forgot I hadn't merged the PR. Nice, thanks!

No, not really, Docker just lets you more easily make sure what is installed on your system (e.g. typically a ubuntu os -- which is what the github action uses anyway; see line 8)

**Review by vegarsti — APPROVED** [review]
⭐️ !

**Pull request merged**
